var hierarchy =
[
    [ "_ascii_kit_host_context", "a01507.html", null ],
    [ "cryptoauthlib.library._CtypeIterator", "a02543.html", null ],
    [ "_kit_host_map_entry", "a01511.html", null ],
    [ "atca_check_mac_in_out", "a01771.html", null ],
    [ "atca_decrypt_in_out", "a01767.html", null ],
    [ "atca_delete_in_out", "a01795.html", null ],
    [ "atca_derive_key_in_out", "a01759.html", null ],
    [ "atca_derive_key_mac_in_out", "a01763.html", null ],
    [ "atca_device", "a01531.html", null ],
    [ "atca_diversified_key_in_out", "a01751.html", null ],
    [ "atca_evp_ctx", "a01827.html", null ],
    [ "atca_gen_dig_in_out", "a01747.html", null ],
    [ "atca_gen_key_in_out", "a01783.html", null ],
    [ "atca_hal_kit_phy_t", "a01671.html", null ],
    [ "atca_hal_list_entry_t", "a01667.html", null ],
    [ "atca_hal_shm_t", "a01675.html", null ],
    [ "atca_hmac_in_out", "a01743.html", null ],
    [ "atca_i2c_host_s", "a01687.html", null ],
    [ "atca_iface", "a01607.html", null ],
    [ "atca_include_data_in_out", "a01715.html", null ],
    [ "atca_io_decrypt_in_out", "a01723.html", null ],
    [ "atca_mac_in_out", "a01739.html", null ],
    [ "atca_mbedtls_eckey_s", "a01823.html", null ],
    [ "atca_nonce_in_out", "a01719.html", null ],
    [ "atca_resp_mac_in_out", "a01775.html", null ],
    [ "atca_secureboot_enc_in_out", "a01731.html", null ],
    [ "atca_secureboot_mac_in_out", "a01735.html", null ],
    [ "atca_session_key_in_out", "a01791.html", null ],
    [ "atca_sha256_ctx", "a01639.html", null ],
    [ "atca_sign_internal_in_out", "a01787.html", null ],
    [ "atca_spi_host_s", "a01691.html", null ],
    [ "atca_temp_key", "a01711.html", null ],
    [ "atca_uart_host_s", "a01695.html", null ],
    [ "atca_verify_in_out", "a01779.html", null ],
    [ "atca_verify_mac", "a01727.html", null ],
    [ "atca_write_mac_in_out", "a01755.html", null ],
    [ "atcac_aes_cmac_ctx", "a01815.html", null ],
    [ "atcac_aes_gcm_ctx", "a01811.html", null ],
    [ "atcac_hmac_ctx", "a01807.html", null ],
    [ "atcac_pk_ctx", "a01819.html", null ],
    [ "atcac_sha1_ctx", "a01803.html", null ],
    [ "atcac_sha2_256_ctx", "a01831.html", null ],
    [ "atcac_sha2_384_ctx", "a01835.html", null ],
    [ "atcac_sha2_512_ctx", "a01839.html", null ],
    [ "atcac_x509_ctx", "a01799.html", null ],
    [ "atcacert_build_state_s", "a01631.html", null ],
    [ "atcacert_cert_element_s", "a01623.html", null ],
    [ "atcacert_cert_loc_s", "a01619.html", null ],
    [ "atcacert_def_s", "a01627.html", null ],
    [ "atcacert_device_loc_s", "a01615.html", null ],
    [ "atcacert_tm_utc_s", "a01611.html", null ],
    [ "ATCAHAL_t", "a01603.html", null ],
    [ "atcaI2Cmaster", "a01679.html", null ],
    [ "ATCAIfaceCfg", "a01539.html", null ],
    [ "ATCAPacket", "a01643.html", null ],
    [ "cryptoauthlib.library.AtcaReference", "a02539.html", null ],
    [ "atcaSWImaster", "a01707.html", null ],
    [ "atecc508a_config_s", "a01651.html", null ],
    [ "atecc608_config_s", "a01655.html", null ],
    [ "atsha204a_config_s", "a01647.html", null ],
    [ "cal_buffer_s", "a01635.html", null ],
    [ "CK_AES_CBC_ENCRYPT_DATA_PARAMS", "a02015.html", null ],
    [ "CK_AES_CCM_PARAMS", "a02123.html", null ],
    [ "CK_AES_CTR_PARAMS", "a02107.html", null ],
    [ "CK_AES_GCM_PARAMS", "a02119.html", null ],
    [ "CK_ARIA_CBC_ENCRYPT_DATA_PARAMS", "a02135.html", null ],
    [ "CK_ATTRIBUTE", "a01935.html", null ],
    [ "CK_C_INITIALIZE_ARGS", "a01951.html", null ],
    [ "CK_CAMELLIA_CBC_ENCRYPT_DATA_PARAMS", "a02131.html", null ],
    [ "CK_CAMELLIA_CTR_PARAMS", "a02127.html", null ],
    [ "CK_CCM_PARAMS", "a02115.html", null ],
    [ "CK_CMS_SIG_PARAMS", "a02075.html", null ],
    [ "CK_DATE", "a01939.html", null ],
    [ "CK_DES_CBC_ENCRYPT_DATA_PARAMS", "a02011.html", null ],
    [ "CK_DSA_PARAMETER_GEN_PARAM", "a02139.html", null ],
    [ "CK_ECDH1_DERIVE_PARAMS", "a01963.html", null ],
    [ "CK_ECDH2_DERIVE_PARAMS", "a01967.html", null ],
    [ "CK_ECDH_AES_KEY_WRAP_PARAMS", "a02143.html", null ],
    [ "CK_ECMQV_DERIVE_PARAMS", "a01971.html", null ],
    [ "CK_FUNCTION_LIST", "a01843.html", null ],
    [ "CK_GCM_PARAMS", "a02111.html", null ],
    [ "CK_GOSTR3410_DERIVE_PARAMS", "a02167.html", null ],
    [ "CK_GOSTR3410_KEY_WRAP_PARAMS", "a02171.html", null ],
    [ "CK_INFO", "a01919.html", null ],
    [ "CK_KEA_DERIVE_PARAMS", "a01987.html", null ],
    [ "CK_KEY_DERIVATION_STRING_DATA", "a02079.html", null ],
    [ "CK_KEY_WRAP_SET_OAEP_PARAMS", "a02031.html", null ],
    [ "CK_KIP_PARAMS", "a02103.html", null ],
    [ "CK_MECHANISM", "a01943.html", null ],
    [ "CK_MECHANISM_INFO", "a01947.html", null ],
    [ "CK_OTP_PARAM", "a02091.html", null ],
    [ "CK_OTP_PARAMS", "a02095.html", null ],
    [ "CK_OTP_SIGNATURE_INFO", "a02099.html", null ],
    [ "CK_PBE_PARAMS", "a02027.html", null ],
    [ "CK_PKCS5_PBKD2_PARAMS", "a02083.html", null ],
    [ "CK_PKCS5_PBKD2_PARAMS2", "a02087.html", null ],
    [ "CK_RC2_CBC_PARAMS", "a01991.html", null ],
    [ "CK_RC2_MAC_GENERAL_PARAMS", "a01995.html", null ],
    [ "CK_RC5_CBC_PARAMS", "a02003.html", null ],
    [ "CK_RC5_MAC_GENERAL_PARAMS", "a02007.html", null ],
    [ "CK_RC5_PARAMS", "a01999.html", null ],
    [ "CK_RSA_AES_KEY_WRAP_PARAMS", "a02147.html", null ],
    [ "CK_RSA_PKCS_OAEP_PARAMS", "a01955.html", null ],
    [ "CK_RSA_PKCS_PSS_PARAMS", "a01959.html", null ],
    [ "CK_SEED_CBC_ENCRYPT_DATA_PARAMS", "a02175.html", null ],
    [ "CK_SESSION_INFO", "a01931.html", null ],
    [ "CK_SKIPJACK_PRIVATE_WRAP_PARAMS", "a02019.html", null ],
    [ "CK_SKIPJACK_RELAYX_PARAMS", "a02023.html", null ],
    [ "CK_SLOT_INFO", "a01923.html", null ],
    [ "CK_SSL3_KEY_MAT_OUT", "a02043.html", null ],
    [ "CK_SSL3_KEY_MAT_PARAMS", "a02047.html", null ],
    [ "CK_SSL3_MASTER_KEY_DERIVE_PARAMS", "a02039.html", null ],
    [ "CK_SSL3_RANDOM_DATA", "a02035.html", null ],
    [ "CK_TLS12_KEY_MAT_PARAMS", "a02155.html", null ],
    [ "CK_TLS12_MASTER_KEY_DERIVE_PARAMS", "a02151.html", null ],
    [ "CK_TLS_KDF_PARAMS", "a02159.html", null ],
    [ "CK_TLS_MAC_PARAMS", "a02163.html", null ],
    [ "CK_TLS_PRF_PARAMS", "a02051.html", null ],
    [ "CK_TOKEN_INFO", "a01927.html", null ],
    [ "CK_VERSION", "a01915.html", null ],
    [ "CK_WTLS_KEY_MAT_OUT", "a02067.html", null ],
    [ "CK_WTLS_KEY_MAT_PARAMS", "a02071.html", null ],
    [ "CK_WTLS_MASTER_KEY_DERIVE_PARAMS", "a02059.html", null ],
    [ "CK_WTLS_PRF_PARAMS", "a02063.html", null ],
    [ "CK_WTLS_RANDOM_DATA", "a02055.html", null ],
    [ "CK_X9_42_DH1_DERIVE_PARAMS", "a01975.html", null ],
    [ "CK_X9_42_DH2_DERIVE_PARAMS", "a01979.html", null ],
    [ "CK_X9_42_MQV_DERIVE_PARAMS", "a01983.html", null ],
    [ "CL_HashContext", "a01663.html", null ],
    [ "device_execution_time_t", "a01659.html", null ],
    [ "devtype_names_t", "a01535.html", null ],
    [ "Exception", null, [
      [ "cryptoauthlib.exceptions.CryptoError", "a02343.html", [
        [ "cryptoauthlib.exceptions.AssertionFailure", "a02451.html", null ],
        [ "cryptoauthlib.exceptions.BadArgumentError", "a02391.html", null ],
        [ "cryptoauthlib.exceptions.BadCrcError", "a02403.html", null ],
        [ "cryptoauthlib.exceptions.BadOpcodeError", "a02439.html", null ],
        [ "cryptoauthlib.exceptions.CheckmacVerifyFailedError", "a02363.html", null ],
        [ "cryptoauthlib.exceptions.CommunicationError", "a02431.html", null ],
        [ "cryptoauthlib.exceptions.ConfigZoneLockedError", "a02351.html", null ],
        [ "cryptoauthlib.exceptions.CrcError", "a02371.html", null ],
        [ "cryptoauthlib.exceptions.DataZoneLockedError", "a02355.html", null ],
        [ "cryptoauthlib.exceptions.EccFaultError", "a02379.html", null ],
        [ "cryptoauthlib.exceptions.ExecutionError", "a02443.html", null ],
        [ "cryptoauthlib.exceptions.FunctionError", "a02383.html", null ],
        [ "cryptoauthlib.exceptions.GenericError", "a02387.html", null ],
        [ "cryptoauthlib.exceptions.HealthTestError", "a02467.html", null ],
        [ "cryptoauthlib.exceptions.InvalidIdentifierError", "a02395.html", null ],
        [ "cryptoauthlib.exceptions.InvalidSizeError", "a02399.html", null ],
        [ "cryptoauthlib.exceptions.LibraryLoadError", "a02347.html", null ],
        [ "cryptoauthlib.exceptions.LibraryMemoryError", "a02471.html", null ],
        [ "cryptoauthlib.exceptions.LibraryNotInitialized", "a02479.html", null ],
        [ "cryptoauthlib.exceptions.NoDevicesFoundError", "a02463.html", null ],
        [ "cryptoauthlib.exceptions.NoResponseError", "a02411.html", null ],
        [ "cryptoauthlib.exceptions.NoUseFlagError", "a02475.html", null ],
        [ "cryptoauthlib.exceptions.ParityError", "a02419.html", null ],
        [ "cryptoauthlib.exceptions.ParseError", "a02367.html", null ],
        [ "cryptoauthlib.exceptions.ReceiveError", "a02407.html", null ],
        [ "cryptoauthlib.exceptions.ReceiveTimeoutError", "a02427.html", null ],
        [ "cryptoauthlib.exceptions.ResyncWithWakeupError", "a02415.html", null ],
        [ "cryptoauthlib.exceptions.StatusUnknownError", "a02375.html", null ],
        [ "cryptoauthlib.exceptions.TimeOutError", "a02435.html", null ],
        [ "cryptoauthlib.exceptions.TransmissionError", "a02455.html", null ],
        [ "cryptoauthlib.exceptions.TransmissionTimeoutError", "a02423.html", null ],
        [ "cryptoauthlib.exceptions.UnimplementedError", "a02447.html", null ],
        [ "cryptoauthlib.exceptions.UnsupportedInterface", "a02483.html", null ],
        [ "cryptoauthlib.exceptions.WakeFailedError", "a02359.html", null ],
        [ "cryptoauthlib.exceptions.ZoneNotLockedError", "a02459.html", null ]
      ] ]
    ] ],
    [ "i2c_sam0_instance", "a01699.html", null ],
    [ "i2c_sam_instance", "a01703.html", null ],
    [ "i2c_start_instance", "a01683.html", null ],
    [ "Jwt", null, [
      [ "cryptoauthlib.atjwt.PyJWT", "a02275.html", null ]
    ] ],
    [ "memory_parameters", "a01523.html", null ],
    [ "object", null, [
      [ "cryptoauthlib_mock.atcab_mock", "a02571.html", null ]
    ] ],
    [ "pcks11_mech_table_e", "a01883.html", null ],
    [ "pkcs11_attrib_model_s", "a01847.html", null ],
    [ "pkcs11_conf_filedata_s", "a01851.html", null ],
    [ "pkcs11_dev_ctx", "a01855.html", null ],
    [ "pkcs11_dev_res", "a01859.html", null ],
    [ "pkcs11_dev_state", "a01863.html", null ],
    [ "pkcs11_ecc_key_info_s", "a01871.html", null ],
    [ "pkcs11_key_info_s", "a01879.html", null ],
    [ "pkcs11_lib_ctx_s", "a01867.html", null ],
    [ "pkcs11_object_cache_s", "a01891.html", null ],
    [ "pkcs11_object_s", "a01887.html", null ],
    [ "pkcs11_rsa_key_info_s", "a01875.html", null ],
    [ "pkcs11_session_ctx_s", "a01907.html", null ],
    [ "pkcs11_session_mech_ctx_s", "a01895.html", null ],
    [ "pkcs11_slot_ctx_s", "a01911.html", null ],
    [ "secure_boot_config_bits", "a01515.html", null ],
    [ "secure_boot_parameters", "a01519.html", null ],
    [ "tng_cert_map_element", "a01527.html", null ],
    [ "Union", null, [
      [ "cryptoauthlib.library.AtcaUnion", "a02547.html", [
        [ "cryptoauthlib.iface._ATCAIfaceParams", "a02531.html", null ],
        [ "cryptoauthlib.iface._U_Address", "a02499.html", null ]
      ] ]
    ] ],
    [ "build_ext", null, [
      [ "setup.CryptoAuthCommandBuildExt", "a02559.html", null ]
    ] ],
    [ "Distribution", null, [
      [ "setup.BinaryDistribution", "a02567.html", null ]
    ] ],
    [ "ECAlgorithm", null, [
      [ "cryptoauthlib.atjwt.HwEcAlgorithm", "a02267.html", null ]
    ] ],
    [ "Enum", null, [
      [ "cryptoauthlib.atcaenum.AtcaEnum", "a02263.html", [
        [ "cryptoauthlib.atcacert.CertStatus", "a02235.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_sn_src_t", "a02215.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_type_t", "a02211.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_date_format_t", "a02227.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_device_zone_t", "a02219.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_std_cert_element_t", "a02231.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_transform_t", "a02223.html", null ],
        [ "cryptoauthlib.iface.ATCADeviceType", "a02495.html", null ],
        [ "cryptoauthlib.iface.ATCAIfaceType", "a02487.html", null ],
        [ "cryptoauthlib.iface.ATCAKitType", "a02491.html", null ],
        [ "cryptoauthlib.status.Status", "a02555.html", null ]
      ] ]
    ] ],
    [ "HMACAlgorithm", null, [
      [ "cryptoauthlib.atjwt.HwHmacAlgorithm", "a02271.html", null ]
    ] ],
    [ "install", null, [
      [ "setup.CryptoAuthCommandInstall", "a02563.html", null ]
    ] ],
    [ "Structure", null, [
      [ "cryptoauthlib.atcab.atca_aes_cbc_ctx", "a02179.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_cbcmac_ctx", "a02203.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_ccm_ctx", "a02199.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_cmac_ctx", "a02183.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_ctr_ctx", "a02187.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_gcm_ctx", "a02195.html", null ],
      [ "cryptoauthlib.atcab.atca_sha256_ctx", "a02191.html", [
        [ "cryptoauthlib.atcab.atca_hmac_sha256_ctx", "a02207.html", null ]
      ] ],
      [ "cryptoauthlib.atcacert.atcacert_tm_utc_t", "a02259.html", null ],
      [ "cryptoauthlib.device.AesEnable", "a02279.html", null ],
      [ "cryptoauthlib.device.ChipMode508", "a02291.html", null ],
      [ "cryptoauthlib.device.ChipMode608", "a02295.html", null ],
      [ "cryptoauthlib.device.ChipOptions", "a02319.html", null ],
      [ "cryptoauthlib.device.CountMatch", "a02287.html", null ],
      [ "cryptoauthlib.device.Counter204", "a02299.html", null ],
      [ "cryptoauthlib.device.I2cEnable", "a02283.html", null ],
      [ "cryptoauthlib.device.KeyConfig", "a02327.html", null ],
      [ "cryptoauthlib.device.SecureBoot", "a02315.html", null ],
      [ "cryptoauthlib.device.SlotConfig", "a02303.html", null ],
      [ "cryptoauthlib.device.UseLock", "a02307.html", null ],
      [ "cryptoauthlib.device.VolatileKeyPermission", "a02311.html", null ],
      [ "cryptoauthlib.device.X509Format", "a02323.html", null ],
      [ "cryptoauthlib.library.AtcaStructure", "a02551.html", [
        [ "cryptoauthlib.atcacert.atcacert_cert_element_t", "a02251.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_loc_t", "a02247.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_comp_data_t", "a02239.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_def_t", "a02255.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_device_loc_t", "a02243.html", null ],
        [ "cryptoauthlib.device.Atecc508aConfig", "a02335.html", null ],
        [ "cryptoauthlib.device.Atecc608Config", "a02339.html", null ],
        [ "cryptoauthlib.device.Atsha204aConfig", "a02331.html", null ],
        [ "cryptoauthlib.iface.ATCAIfaceCfg", "a02535.html", null ],
        [ "cryptoauthlib.iface._ATCACUSTOM", "a02527.html", null ],
        [ "cryptoauthlib.iface._ATCAHID", "a02519.html", null ],
        [ "cryptoauthlib.iface._ATCAI2C", "a02503.html", null ],
        [ "cryptoauthlib.iface._ATCAKIT", "a02523.html", null ],
        [ "cryptoauthlib.iface._ATCASPI", "a02511.html", null ],
        [ "cryptoauthlib.iface._ATCASWI", "a02507.html", null ],
        [ "cryptoauthlib.iface._ATCAUART", "a02515.html", null ]
      ] ]
    ] ]
];