var hierarchy =
[
    [ "_ascii_kit_host_context", "a01540.html", null ],
    [ "cryptoauthlib.library._CtypeIterator", "a02576.html", null ],
    [ "_kit_host_map_entry", "a01544.html", null ],
    [ "atca_check_mac_in_out", "a01804.html", null ],
    [ "atca_decrypt_in_out", "a01800.html", null ],
    [ "atca_delete_in_out", "a01828.html", null ],
    [ "atca_derive_key_in_out", "a01792.html", null ],
    [ "atca_derive_key_mac_in_out", "a01796.html", null ],
    [ "atca_device", "a01560.html", null ],
    [ "atca_diversified_key_in_out", "a01784.html", null ],
    [ "atca_evp_ctx", "a01860.html", null ],
    [ "atca_gen_dig_in_out", "a01780.html", null ],
    [ "atca_gen_key_in_out", "a01816.html", null ],
    [ "atca_hal_kit_phy_t", "a01704.html", null ],
    [ "atca_hal_list_entry_t", "a01700.html", null ],
    [ "atca_hal_shm_t", "a01708.html", null ],
    [ "atca_hmac_in_out", "a01776.html", null ],
    [ "atca_i2c_host_s", "a01720.html", null ],
    [ "atca_iface", "a01636.html", null ],
    [ "atca_include_data_in_out", "a01748.html", null ],
    [ "atca_io_decrypt_in_out", "a01756.html", null ],
    [ "atca_mac_in_out", "a01772.html", null ],
    [ "atca_mbedtls_eckey_s", "a01856.html", null ],
    [ "atca_nonce_in_out", "a01752.html", null ],
    [ "atca_resp_mac_in_out", "a01808.html", null ],
    [ "atca_secureboot_enc_in_out", "a01764.html", null ],
    [ "atca_secureboot_mac_in_out", "a01768.html", null ],
    [ "atca_session_key_in_out", "a01824.html", null ],
    [ "atca_sha256_ctx", "a01668.html", null ],
    [ "atca_sign_internal_in_out", "a01820.html", null ],
    [ "atca_spi_host_s", "a01724.html", null ],
    [ "atca_temp_key", "a01744.html", null ],
    [ "atca_uart_host_s", "a01728.html", null ],
    [ "atca_verify_in_out", "a01812.html", null ],
    [ "atca_verify_mac", "a01760.html", null ],
    [ "atca_write_mac_in_out", "a01788.html", null ],
    [ "atcac_aes_cmac_ctx", "a01848.html", null ],
    [ "atcac_aes_gcm_ctx", "a01844.html", null ],
    [ "atcac_hmac_ctx", "a01840.html", null ],
    [ "atcac_pk_ctx", "a01852.html", null ],
    [ "atcac_sha1_ctx", "a01836.html", null ],
    [ "atcac_sha2_256_ctx", "a01864.html", null ],
    [ "atcac_sha2_384_ctx", "a01868.html", null ],
    [ "atcac_sha2_512_ctx", "a01872.html", null ],
    [ "atcac_x509_ctx", "a01832.html", null ],
    [ "atcacert_build_state_s", "a01660.html", null ],
    [ "atcacert_cert_element_s", "a01652.html", null ],
    [ "atcacert_cert_loc_s", "a01648.html", null ],
    [ "atcacert_def_s", "a01656.html", null ],
    [ "atcacert_device_loc_s", "a01644.html", null ],
    [ "atcacert_tm_utc_s", "a01640.html", null ],
    [ "ATCAHAL_t", "a01632.html", null ],
    [ "atcaI2Cmaster", "a01712.html", null ],
    [ "ATCAIfaceCfg", "a01568.html", null ],
    [ "ATCAPacket", "a01672.html", null ],
    [ "cryptoauthlib.library.AtcaReference", "a02572.html", null ],
    [ "atcaSWImaster", "a01740.html", null ],
    [ "atecc508a_config_s", "a01680.html", null ],
    [ "atecc608_config_s", "a01684.html", null ],
    [ "atsha204a_config_s", "a01676.html", null ],
    [ "cal_buffer_s", "a01664.html", null ],
    [ "calib_packet_cache_s", "a01692.html", null ],
    [ "CK_AES_CBC_ENCRYPT_DATA_PARAMS", "a02048.html", null ],
    [ "CK_AES_CCM_PARAMS", "a02156.html", null ],
    [ "CK_AES_CTR_PARAMS", "a02140.html", null ],
    [ "CK_AES_GCM_PARAMS", "a02152.html", null ],
    [ "CK_ARIA_CBC_ENCRYPT_DATA_PARAMS", "a02168.html", null ],
    [ "CK_ATTRIBUTE", "a01968.html", null ],
    [ "CK_C_INITIALIZE_ARGS", "a01984.html", null ],
    [ "CK_CAMELLIA_CBC_ENCRYPT_DATA_PARAMS", "a02164.html", null ],
    [ "CK_CAMELLIA_CTR_PARAMS", "a02160.html", null ],
    [ "CK_CCM_PARAMS", "a02148.html", null ],
    [ "CK_CMS_SIG_PARAMS", "a02108.html", null ],
    [ "CK_DATE", "a01972.html", null ],
    [ "CK_DES_CBC_ENCRYPT_DATA_PARAMS", "a02044.html", null ],
    [ "CK_DSA_PARAMETER_GEN_PARAM", "a02172.html", null ],
    [ "CK_ECDH1_DERIVE_PARAMS", "a01996.html", null ],
    [ "CK_ECDH2_DERIVE_PARAMS", "a02000.html", null ],
    [ "CK_ECDH_AES_KEY_WRAP_PARAMS", "a02176.html", null ],
    [ "CK_ECMQV_DERIVE_PARAMS", "a02004.html", null ],
    [ "CK_FUNCTION_LIST", "a01876.html", null ],
    [ "CK_GCM_PARAMS", "a02144.html", null ],
    [ "CK_GOSTR3410_DERIVE_PARAMS", "a02200.html", null ],
    [ "CK_GOSTR3410_KEY_WRAP_PARAMS", "a02204.html", null ],
    [ "CK_INFO", "a01952.html", null ],
    [ "CK_KEA_DERIVE_PARAMS", "a02020.html", null ],
    [ "CK_KEY_DERIVATION_STRING_DATA", "a02112.html", null ],
    [ "CK_KEY_WRAP_SET_OAEP_PARAMS", "a02064.html", null ],
    [ "CK_KIP_PARAMS", "a02136.html", null ],
    [ "CK_MECHANISM", "a01976.html", null ],
    [ "CK_MECHANISM_INFO", "a01980.html", null ],
    [ "CK_OTP_PARAM", "a02124.html", null ],
    [ "CK_OTP_PARAMS", "a02128.html", null ],
    [ "CK_OTP_SIGNATURE_INFO", "a02132.html", null ],
    [ "CK_PBE_PARAMS", "a02060.html", null ],
    [ "CK_PKCS5_PBKD2_PARAMS", "a02116.html", null ],
    [ "CK_PKCS5_PBKD2_PARAMS2", "a02120.html", null ],
    [ "CK_RC2_CBC_PARAMS", "a02024.html", null ],
    [ "CK_RC2_MAC_GENERAL_PARAMS", "a02028.html", null ],
    [ "CK_RC5_CBC_PARAMS", "a02036.html", null ],
    [ "CK_RC5_MAC_GENERAL_PARAMS", "a02040.html", null ],
    [ "CK_RC5_PARAMS", "a02032.html", null ],
    [ "CK_RSA_AES_KEY_WRAP_PARAMS", "a02180.html", null ],
    [ "CK_RSA_PKCS_OAEP_PARAMS", "a01988.html", null ],
    [ "CK_RSA_PKCS_PSS_PARAMS", "a01992.html", null ],
    [ "CK_SEED_CBC_ENCRYPT_DATA_PARAMS", "a02208.html", null ],
    [ "CK_SESSION_INFO", "a01964.html", null ],
    [ "CK_SKIPJACK_PRIVATE_WRAP_PARAMS", "a02052.html", null ],
    [ "CK_SKIPJACK_RELAYX_PARAMS", "a02056.html", null ],
    [ "CK_SLOT_INFO", "a01956.html", null ],
    [ "CK_SSL3_KEY_MAT_OUT", "a02076.html", null ],
    [ "CK_SSL3_KEY_MAT_PARAMS", "a02080.html", null ],
    [ "CK_SSL3_MASTER_KEY_DERIVE_PARAMS", "a02072.html", null ],
    [ "CK_SSL3_RANDOM_DATA", "a02068.html", null ],
    [ "CK_TLS12_KEY_MAT_PARAMS", "a02188.html", null ],
    [ "CK_TLS12_MASTER_KEY_DERIVE_PARAMS", "a02184.html", null ],
    [ "CK_TLS_KDF_PARAMS", "a02192.html", null ],
    [ "CK_TLS_MAC_PARAMS", "a02196.html", null ],
    [ "CK_TLS_PRF_PARAMS", "a02084.html", null ],
    [ "CK_TOKEN_INFO", "a01960.html", null ],
    [ "CK_VERSION", "a01948.html", null ],
    [ "CK_WTLS_KEY_MAT_OUT", "a02100.html", null ],
    [ "CK_WTLS_KEY_MAT_PARAMS", "a02104.html", null ],
    [ "CK_WTLS_MASTER_KEY_DERIVE_PARAMS", "a02092.html", null ],
    [ "CK_WTLS_PRF_PARAMS", "a02096.html", null ],
    [ "CK_WTLS_RANDOM_DATA", "a02088.html", null ],
    [ "CK_X9_42_DH1_DERIVE_PARAMS", "a02008.html", null ],
    [ "CK_X9_42_DH2_DERIVE_PARAMS", "a02012.html", null ],
    [ "CK_X9_42_MQV_DERIVE_PARAMS", "a02016.html", null ],
    [ "CL_HashContext", "a01696.html", null ],
    [ "device_execution_time_t", "a01688.html", null ],
    [ "devtype_names_t", "a01564.html", null ],
    [ "Exception", null, [
      [ "cryptoauthlib.exceptions.CryptoError", "a02376.html", [
        [ "cryptoauthlib.exceptions.AssertionFailure", "a02484.html", null ],
        [ "cryptoauthlib.exceptions.BadArgumentError", "a02424.html", null ],
        [ "cryptoauthlib.exceptions.BadCrcError", "a02436.html", null ],
        [ "cryptoauthlib.exceptions.BadOpcodeError", "a02472.html", null ],
        [ "cryptoauthlib.exceptions.CheckmacVerifyFailedError", "a02396.html", null ],
        [ "cryptoauthlib.exceptions.CommunicationError", "a02464.html", null ],
        [ "cryptoauthlib.exceptions.ConfigZoneLockedError", "a02384.html", null ],
        [ "cryptoauthlib.exceptions.CrcError", "a02404.html", null ],
        [ "cryptoauthlib.exceptions.DataZoneLockedError", "a02388.html", null ],
        [ "cryptoauthlib.exceptions.EccFaultError", "a02412.html", null ],
        [ "cryptoauthlib.exceptions.ExecutionError", "a02476.html", null ],
        [ "cryptoauthlib.exceptions.FunctionError", "a02416.html", null ],
        [ "cryptoauthlib.exceptions.GenericError", "a02420.html", null ],
        [ "cryptoauthlib.exceptions.HealthTestError", "a02500.html", null ],
        [ "cryptoauthlib.exceptions.InvalidIdentifierError", "a02428.html", null ],
        [ "cryptoauthlib.exceptions.InvalidSizeError", "a02432.html", null ],
        [ "cryptoauthlib.exceptions.LibraryLoadError", "a02380.html", null ],
        [ "cryptoauthlib.exceptions.LibraryMemoryError", "a02504.html", null ],
        [ "cryptoauthlib.exceptions.LibraryNotInitialized", "a02512.html", null ],
        [ "cryptoauthlib.exceptions.NoDevicesFoundError", "a02496.html", null ],
        [ "cryptoauthlib.exceptions.NoResponseError", "a02444.html", null ],
        [ "cryptoauthlib.exceptions.NoUseFlagError", "a02508.html", null ],
        [ "cryptoauthlib.exceptions.ParityError", "a02452.html", null ],
        [ "cryptoauthlib.exceptions.ParseError", "a02400.html", null ],
        [ "cryptoauthlib.exceptions.ReceiveError", "a02440.html", null ],
        [ "cryptoauthlib.exceptions.ReceiveTimeoutError", "a02460.html", null ],
        [ "cryptoauthlib.exceptions.ResyncWithWakeupError", "a02448.html", null ],
        [ "cryptoauthlib.exceptions.StatusUnknownError", "a02408.html", null ],
        [ "cryptoauthlib.exceptions.TimeOutError", "a02468.html", null ],
        [ "cryptoauthlib.exceptions.TransmissionError", "a02488.html", null ],
        [ "cryptoauthlib.exceptions.TransmissionTimeoutError", "a02456.html", null ],
        [ "cryptoauthlib.exceptions.UnimplementedError", "a02480.html", null ],
        [ "cryptoauthlib.exceptions.UnsupportedInterface", "a02516.html", null ],
        [ "cryptoauthlib.exceptions.WakeFailedError", "a02392.html", null ],
        [ "cryptoauthlib.exceptions.ZoneNotLockedError", "a02492.html", null ]
      ] ]
    ] ],
    [ "i2c_sam0_instance", "a01732.html", null ],
    [ "i2c_sam_instance", "a01736.html", null ],
    [ "i2c_start_instance", "a01716.html", null ],
    [ "Jwt", null, [
      [ "cryptoauthlib.atjwt.PyJWT", "a02308.html", null ]
    ] ],
    [ "memory_parameters", "a01556.html", null ],
    [ "object", null, [
      [ "cryptoauthlib_mock.atcab_mock", "a02608.html", null ]
    ] ],
    [ "pcks11_mech_table_e", "a01916.html", null ],
    [ "pkcs11_attrib_model_s", "a01880.html", null ],
    [ "pkcs11_conf_filedata_s", "a01884.html", null ],
    [ "pkcs11_dev_ctx", "a01888.html", null ],
    [ "pkcs11_dev_res", "a01892.html", null ],
    [ "pkcs11_dev_state", "a01896.html", null ],
    [ "pkcs11_ecc_key_info_s", "a01904.html", null ],
    [ "pkcs11_key_info_s", "a01912.html", null ],
    [ "pkcs11_lib_ctx_s", "a01900.html", null ],
    [ "pkcs11_object_cache_s", "a01924.html", null ],
    [ "pkcs11_object_s", "a01920.html", null ],
    [ "pkcs11_rsa_key_info_s", "a01908.html", null ],
    [ "pkcs11_session_ctx_s", "a01940.html", null ],
    [ "pkcs11_session_mech_ctx_s", "a01928.html", null ],
    [ "pkcs11_slot_ctx_s", "a01944.html", null ],
    [ "secure_boot_config_bits", "a01548.html", null ],
    [ "secure_boot_parameters", "a01552.html", null ],
    [ "Union", null, [
      [ "cryptoauthlib.library.AtcaUnion", "a02580.html", [
        [ "cryptoauthlib.iface._ATCAIfaceParams", "a02564.html", null ],
        [ "cryptoauthlib.iface._U_Address", "a02532.html", null ]
      ] ]
    ] ],
    [ "build_ext", null, [
      [ "setup.CryptoAuthCommandBuildExt", "a02596.html", null ]
    ] ],
    [ "Distribution", null, [
      [ "setup.BinaryDistribution", "a02604.html", null ]
    ] ],
    [ "ECAlgorithm", null, [
      [ "cryptoauthlib.atjwt.HwEcAlgorithm", "a02300.html", null ]
    ] ],
    [ "Enum", null, [
      [ "cryptoauthlib.atcaenum.AtcaEnum", "a02296.html", [
        [ "cryptoauthlib.atcacert.CertStatus", "a02268.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_sn_src_t", "a02248.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_type_t", "a02244.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_date_format_t", "a02260.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_device_zone_t", "a02252.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_std_cert_element_t", "a02264.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_transform_t", "a02256.html", null ],
        [ "cryptoauthlib.iface.ATCADeviceType", "a02528.html", null ],
        [ "cryptoauthlib.iface.ATCAIfaceType", "a02520.html", null ],
        [ "cryptoauthlib.iface.ATCAKitType", "a02524.html", null ],
        [ "cryptoauthlib.status.Status", "a02592.html", null ]
      ] ]
    ] ],
    [ "HMACAlgorithm", null, [
      [ "cryptoauthlib.atjwt.HwHmacAlgorithm", "a02304.html", null ]
    ] ],
    [ "install", null, [
      [ "setup.CryptoAuthCommandInstall", "a02600.html", null ]
    ] ],
    [ "Structure", null, [
      [ "cryptoauthlib.atcab.atca_aes_cbc_ctx", "a02212.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_cbcmac_ctx", "a02236.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_ccm_ctx", "a02232.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_cmac_ctx", "a02216.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_ctr_ctx", "a02220.html", null ],
      [ "cryptoauthlib.atcab.atca_aes_gcm_ctx", "a02228.html", null ],
      [ "cryptoauthlib.atcab.atca_sha256_ctx", "a02224.html", [
        [ "cryptoauthlib.atcab.atca_hmac_sha256_ctx", "a02240.html", null ]
      ] ],
      [ "cryptoauthlib.atcacert.atcacert_tm_utc_t", "a02292.html", null ],
      [ "cryptoauthlib.device.AesEnable", "a02312.html", null ],
      [ "cryptoauthlib.device.ChipMode508", "a02324.html", null ],
      [ "cryptoauthlib.device.ChipMode608", "a02328.html", null ],
      [ "cryptoauthlib.device.ChipOptions", "a02352.html", null ],
      [ "cryptoauthlib.device.CountMatch", "a02320.html", null ],
      [ "cryptoauthlib.device.Counter204", "a02332.html", null ],
      [ "cryptoauthlib.device.I2cEnable", "a02316.html", null ],
      [ "cryptoauthlib.device.KeyConfig", "a02360.html", null ],
      [ "cryptoauthlib.device.SecureBoot", "a02348.html", null ],
      [ "cryptoauthlib.device.SlotConfig", "a02336.html", null ],
      [ "cryptoauthlib.device.UseLock", "a02340.html", null ],
      [ "cryptoauthlib.device.VolatileKeyPermission", "a02344.html", null ],
      [ "cryptoauthlib.device.X509Format", "a02356.html", null ],
      [ "cryptoauthlib.library.AtcaStructure", "a02584.html", [
        [ "cryptoauthlib.atcacert.atcacert_cert_element_t", "a02284.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_cert_loc_t", "a02280.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_comp_data_t", "a02272.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_def_t", "a02288.html", null ],
        [ "cryptoauthlib.atcacert.atcacert_device_loc_t", "a02276.html", null ],
        [ "cryptoauthlib.device.Atecc508aConfig", "a02368.html", null ],
        [ "cryptoauthlib.device.Atecc608Config", "a02372.html", null ],
        [ "cryptoauthlib.device.Atsha204aConfig", "a02364.html", null ],
        [ "cryptoauthlib.iface.ATCAIfaceCfg", "a02568.html", null ],
        [ "cryptoauthlib.iface._ATCACUSTOM", "a02560.html", null ],
        [ "cryptoauthlib.iface._ATCAHID", "a02552.html", null ],
        [ "cryptoauthlib.iface._ATCAI2C", "a02536.html", null ],
        [ "cryptoauthlib.iface._ATCAKIT", "a02556.html", null ],
        [ "cryptoauthlib.iface._ATCASPI", "a02544.html", null ],
        [ "cryptoauthlib.iface._ATCASWI", "a02540.html", null ],
        [ "cryptoauthlib.iface._ATCAUART", "a02548.html", null ],
        [ "cryptoauthlib.library.cal_buffer", "a02588.html", null ]
      ] ]
    ] ]
];