/**
 * \file
 * \brief CryptoAuthLib Basic API methods for KDF command.
 *
 * The KDF command implements one of a number of Key Derivation Functions (KDF).
 * Generally this function combines a source key with an input string and
 * creates a result key/digest/array. Three algorithms are currently supported:
 * PRF, HKDF and AES.
 *
 * \note List of devices that support this command - ATECC608A/B. Refer to device
 *       datasheet for full details.
 *
 * \copyright (c) 2015-2020 Microchip Technology Inc. and its subsidiaries.
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip software
 * and any derivatives exclusively with Microchip products. It is your
 * responsibility to comply with third party license terms applicable to your
 * use of third party software (including open source software) that may
 * accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 * PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT,
 * SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE
 * OF ANY KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF
 * MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE
 * FORESEEABLE. TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL
 * LIABILITY ON ALL CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED
 * THE AMOUNT OF FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR
 * THIS SOFTWARE.
 */

#include "cryptoauthlib.h"

#if CALIB_KDF_EN
/** \brief Executes the KDF command, which derives a new key in PRF, AES, or
 *          HKDF modes.
 *
 * Generally this function combines a source key with an input string and
 * creates a result key/digest/array.
 *
 * \param[in]  device     Device context pointer
 * \param[in]  mode       Mode determines KDF algorithm (PRF,AES,HKDF), source
 *                        key location, and target key locations.
 * \param[in]  key_id     Source and target key slots if locations are in the
 *                        EEPROM. Source key slot is the LSB and target key
 *                        slot is the MSB.
 * \param[in]  details    Further information about the computation, depending
 *                        on the algorithm (4 bytes).
 * \param[in]  message    Input value from system (up to 128 bytes). Actual size
 *                        of message is 16 bytes for AES algorithm or is encoded
 *                        in the MSB of the details parameter for other
 *                        algorithms.
 * \param[out] out_data   Output of the KDF function is returned here. If the
 *                        result remains in the device, this can be NULL.
 * \param[out] out_nonce  If the output is encrypted, a 32 byte random nonce
 *                        generated by the device is returned here. If output
 *                        encryption is not used, this can be NULL.
 *
 * \return ATCA_SUCCESS on success, otherwise an error code.
 */
ATCA_STATUS calib_kdf(ATCADevice device, uint8_t mode, uint16_t key_id, const uint32_t details, const uint8_t* message, uint8_t* out_data, uint8_t* out_nonce)
{
    ATCAPacket * packet = NULL;
    ATCA_STATUS status;
    uint16_t out_data_size = 0;

    do
    {
        if ((device == NULL) || (message == NULL))
        {
            status = ATCA_TRACE(ATCA_BAD_PARAM, "NULL pointer received");
            break;
        }

        packet = calib_packet_alloc();
        if(NULL == packet)
        {
            (void)ATCA_TRACE(ATCA_ALLOC_FAILURE, "calib_packet_alloc - failed");
            status = ATCA_ALLOC_FAILURE;
            break;
        }

        (void)memset(packet, 0x00, sizeof(ATCAPacket));

        // Build the KDF command
        packet->param1 = mode;
        packet->param2 = key_id;

        // Add details parameter
        packet->data[0] = (uint8_t)(details & 0x000000FFu);
        packet->data[1] = (uint8_t)((details & 0x0000FF00u) >> 8u);
        packet->data[2] = (uint8_t)((details & 0x00FF0000u) >> 16u);
        packet->data[3] = (uint8_t)((details & 0xFF000000u) >> 24u);

        #if (CA_MAX_PACKET_SIZE < (ATCA_CMD_SIZE_MIN + KDF_DETAILS_SIZE + AES_DATA_SIZE))
        #if ATCA_PREPROCESSOR_WARNING
        #warning "CA_MAX_PACKET_SIZE will not support KDF mode AES algorithm"
        #endif
        if ((mode & KDF_MODE_ALG_MASK) == KDF_MODE_ALG_AES)
        {
            status = ATCA_TRACE(ATCA_INVALID_SIZE, "KDF mode AES algorithm is not supported");
        }
        #endif

        if (((mode & KDF_MODE_ALG_MASK) != KDF_MODE_ALG_AES) && (CA_MAX_PACKET_SIZE < (ATCA_CMD_SIZE_MIN + KDF_DETAILS_SIZE + (packet->data[3] & 0xFFu))))
        {
            status = ATCA_TRACE(ATCA_INVALID_SIZE, "Invalid packet size received");
            break;
        }

        // Add input message
        if ((mode & KDF_MODE_ALG_MASK) == KDF_MODE_ALG_AES)
        {
            // AES algorithm has a fixed message size
            (void)memcpy(&packet->data[KDF_DETAILS_SIZE], message, AES_DATA_SIZE);
        }
        else
        {
            // All other algorithms encode message size in the last byte of details
            (void)memcpy(&packet->data[KDF_DETAILS_SIZE], message, packet->data[3]);
        }

        // Build command
        if ((status = atKDF(atcab_get_device_type_ext(device), packet)) != ATCA_SUCCESS)
        {
            (void)ATCA_TRACE(status, "atKDF - failed");
            break;
        }

        // Run command
        if ((status = atca_execute_command(packet, device)) != ATCA_SUCCESS)
        {
            (void)ATCA_TRACE(status, "calib_kdf - execution failed");
            break;
        }

        if (((mode & KDF_MODE_ALG_MASK) == KDF_MODE_ALG_PRF) && ((details & KDF_DETAILS_PRF_TARGET_LEN_64) == KDF_DETAILS_PRF_TARGET_LEN_64))
        {
            out_data_size = 64;
        }
        else
        {
            out_data_size = 32;
        }

        // Return OutData if possible
        if (out_data != NULL && packet->data[ATCA_COUNT_IDX] >= (ATCA_PACKET_OVERHEAD + out_data_size))
        {
            if (CA_MAX_PACKET_SIZE < (ATCA_PACKET_OVERHEAD + out_data_size))
            {
                (void)ATCA_TRACE(ATCA_INVALID_SIZE, "Invalid packet size received");
                break;
            }
            (void)memcpy(out_data, &packet->data[ATCA_RSP_DATA_IDX], out_data_size);
        }

        // return OutNonce if possible
        if (out_nonce != NULL && packet->data[ATCA_COUNT_IDX] >= (ATCA_PACKET_OVERHEAD + out_data_size + 32u))
        {
            if (CA_MAX_PACKET_SIZE < (ATCA_PACKET_OVERHEAD + out_data_size + 32u))
            {
                (void)ATCA_TRACE(ATCA_INVALID_SIZE, "Invalid packet size received");
                break;
            }
            (void)memcpy(out_nonce, &packet->data[ATCA_RSP_DATA_IDX + out_data_size], 32);
        }
    } while (false);

    calib_packet_free(packet);
    return status;
}
#endif  /* CALIB_KDF */
